"""empty message

Revision ID: 006000f74e99
Revises: 1a4fb3246757
Create Date: 2020-10-09 13:57:12.265388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006000f74e99'
down_revision = '1a4fb3246757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChucDanhCongTacUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Chuc_Danh_Cong_Tac_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['Chuc_Danh_Cong_Tac_id'], ['ChucDanhCongTac.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Dm_ChucDanhCongTac')
    op.add_column('ChucDanhCongTac', sa.Column('ten', sa.NVARCHAR(length=100), nullable=True))
    op.drop_constraint('FK__ChucDanhC__Chuc___0C85DE4D', 'ChucDanhCongTac', type_='foreignkey')
    op.drop_constraint('FK__ChucDanhC__user___0B91BA14', 'ChucDanhCongTac', type_='foreignkey')
    op.drop_column('ChucDanhCongTac', 'ngay_bat_dau')
    op.drop_column('ChucDanhCongTac', 'Chuc_Danh_Cong_Tac_id')
    op.drop_column('ChucDanhCongTac', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChucDanhCongTac', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ChucDanhCongTac', sa.Column('Chuc_Danh_Cong_Tac_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('ChucDanhCongTac', sa.Column('ngay_bat_dau', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key('FK__ChucDanhC__user___0B91BA14', 'ChucDanhCongTac', 'User', ['user_id'], ['id'])
    op.create_foreign_key('FK__ChucDanhC__Chuc___0C85DE4D', 'ChucDanhCongTac', 'Dm_ChucDanhCongTac', ['Chuc_Danh_Cong_Tac_id'], ['id'])
    op.drop_column('ChucDanhCongTac', 'ten')
    op.create_table('Dm_ChucDanhCongTac',
    sa.Column('id', sa.SMALLINT(), autoincrement=True, nullable=False, mssql_identity_start=1, mssql_identity_increment=1),
    sa.Column('ten', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__Dm_ChucD__3213E83F9C8A3A7C')
    )
    op.drop_table('ChucDanhCongTacUser')
    # ### end Alembic commands ###
