"""empty message

Revision ID: 04a2aca5da47
Revises: c46e4184f971
Create Date: 2020-10-12 10:48:51.730282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a2aca5da47'
down_revision = 'c46e4184f971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test', 'User', ['id'], ['id'], referent_schema='NhanSu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    # ### end Alembic commands ###
