"""empty message

Revision ID: 09ceba7b260e
Revises: e296be8d41df
Create Date: 2020-10-09 14:01:40.868672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ceba7b260e'
down_revision = 'e296be8d41df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChucDanhCongTacUser', sa.Column('chuc_danh_cong_tac_id', sa.SMALLINT(), nullable=True))
    op.drop_constraint('FK__ChucDanhC__Chuc___236943A5', 'ChucDanhCongTacUser', type_='foreignkey')
    op.create_foreign_key(None, 'ChucDanhCongTacUser', 'ChucDanhCongTac', ['chuc_danh_cong_tac_id'], ['id'])
    op.drop_column('ChucDanhCongTacUser', 'Chuc_Danh_Cong_Tac_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChucDanhCongTacUser', sa.Column('Chuc_Danh_Cong_Tac_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ChucDanhCongTacUser', type_='foreignkey')
    op.create_foreign_key('FK__ChucDanhC__Chuc___236943A5', 'ChucDanhCongTacUser', 'ChucDanhCongTac', ['Chuc_Danh_Cong_Tac_id'], ['id'])
    op.drop_column('ChucDanhCongTacUser', 'chuc_danh_cong_tac_id')
    # ### end Alembic commands ###
