"""empty message

Revision ID: 19fc8f5beffe
Revises: d3ff2aa3d4a6
Create Date: 2020-10-08 16:55:26.521028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '19fc8f5beffe'
down_revision = 'd3ff2aa3d4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('nam_gioi', sa.NCHAR(length=1), nullable=True),
    sa.Column('nhom_mau', sa.String(length=10), nullable=True),
    sa.Column('dan_toc', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('noi_o', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('so_hieu', sa.String(length=6), nullable=True),
    sa.Column('ngay_vao_cong_an', sa.Date(), nullable=True),
    sa.Column('nganh_ngoai', sa.Boolean(), nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trang_thai_user_id', sa.SMALLINT(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trang_thai_user_id'], ['TrangThaiUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_ten'), 'User', ['ten'], unique=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.drop_index('ix_User_ten', table_name='Users')
    op.drop_table('Users')
    op.create_foreign_key(None, 'SoDienThoai', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SoDienThoai', type_='foreignkey')
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, mssql_identity_start=1, mssql_identity_increment=1),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ngay_sinh', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nam_gioi', sa.NCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('nhom_mau', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dan_toc', sa.NVARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('noi_o', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('so_hieu', sa.VARCHAR(length=6, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ngay_vao_cong_an', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nganh_ngoai', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trang_thai_user_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__User__3213E83F61040B2E')
    )
    op.create_index('ix_User_ten', 'Users', ['ten'], unique=False)
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_ten'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
