"""empty message

Revision ID: 1a4fb3246757
Revises: ffbd1a873aca
Create Date: 2020-10-09 13:52:02.175759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4fb3246757'
down_revision = 'ffbd1a873aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChucDanhCongTac', sa.Column('Chuc_Danh_Cong_Tac_id', sa.SMALLINT(), nullable=True))
    op.drop_constraint('FK__ChucDanhC__Dm_Ch__0A9D95DB', 'ChucDanhCongTac', type_='foreignkey')
    op.create_foreign_key(None, 'ChucDanhCongTac', 'Dm_ChucDanhCongTac', ['Chuc_Danh_Cong_Tac_id'], ['id'])
    op.drop_column('ChucDanhCongTac', 'Dm_Chuc_Danh_Cong_Tac_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChucDanhCongTac', sa.Column('Dm_Chuc_Danh_Cong_Tac_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ChucDanhCongTac', type_='foreignkey')
    op.create_foreign_key('FK__ChucDanhC__Dm_Ch__0A9D95DB', 'ChucDanhCongTac', 'Dm_ChucDanhCongTac', ['Dm_Chuc_Danh_Cong_Tac_id'], ['id'])
    op.drop_column('ChucDanhCongTac', 'Chuc_Danh_Cong_Tac_id')
    # ### end Alembic commands ###
