"""empty message

Revision ID: 1bdbb1e4095c
Revises: 241184c0a524
Create Date: 2020-10-05 10:11:28.581795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdbb1e4095c'
down_revision = '241184c0a524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('ngay_vao_cong_an', sa.Date(), nullable=True))
    op.add_column('User', sa.Column('noi_o', sa.NVARCHAR(length=100), nullable=True))
    op.drop_column('User', 'ngay_vao_ca')
    op.drop_column('User', 'noio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('noio', sa.NVARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('ngay_vao_ca', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('User', 'noi_o')
    op.drop_column('User', 'ngay_vao_cong_an')
    # ### end Alembic commands ###
