"""empty message

Revision ID: 213fe607e29a
Revises: 996331167405
Create Date: 2020-10-04 10:35:06.712542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213fe607e29a'
down_revision = '996331167405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CanBo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('HoDem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('Ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CanBo_email'), 'CanBo', ['email'], unique=True)
    op.create_index(op.f('ix_CanBo_username'), 'CanBo', ['username'], unique=True)
    op.drop_table('can_bo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('can_bo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, mssql_identity_start=1, mssql_identity_increment=1),
    sa.Column('HoDem', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('Ten', sa.NVARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__can_bo__3213E83F0BB26ED4')
    )
    op.drop_index(op.f('ix_CanBo_username'), table_name='CanBo')
    op.drop_index(op.f('ix_CanBo_email'), table_name='CanBo')
    op.drop_table('CanBo')
    # ### end Alembic commands ###
