"""empty message

Revision ID: 26abcbf8e9bb
Revises: d86ffa0a81d1
Create Date: 2020-10-13 09:48:44.925793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26abcbf8e9bb'
down_revision = 'd86ffa0a81d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PltdTapThe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nam', sa.SMALLINT(), nullable=True),
    sa.Column('phan_loai', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('ghi_chu', sa.NVARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PltdTapThe', schema='NhanSu')
    # ### end Alembic commands ###
