"""empty message

Revision ID: 34067553f0be
Revises: 0f6c5a1731d4
Create Date: 2020-10-04 18:16:46.734068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34067553f0be'
down_revision = '0f6c5a1731d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('NgaySinh', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'NgaySinh')
    # ### end Alembic commands ###
