"""empty message

Revision ID: 38a03513ac6c
Revises: 97c65307198c
Create Date: 2020-10-13 09:34:00.834835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a03513ac6c'
down_revision = '97c65307198c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DangDoanThe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('can_bo_id', sa.INTEGER(), nullable=True),
    sa.Column('ngay_vao_dang_lan_dau', sa.DATE(), nullable=True),
    sa.Column('ngay_vao_dang_chinh_thuc', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['can_bo_id'], ['NhanSu.CanBo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DangDoanThe', schema='NhanSu')
    # ### end Alembic commands ###
