"""empty message

Revision ID: 3bb932cad882
Revises: 332bddd30f6d
Create Date: 2020-10-11 09:51:20.337032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb932cad882'
down_revision = '332bddd30f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__ChucDanhC__user___6D0D32F4', 'ChucDanhCongTac', schema='NhanSu', type_='foreignkey')
    op.drop_column('ChucDanhCongTac', 'user_id', schema='NhanSu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChucDanhCongTac', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='NhanSu')
    op.create_foreign_key('FK__ChucDanhC__user___6D0D32F4', 'ChucDanhCongTac', 'User', ['user_id'], ['id'], source_schema='NhanSu', referent_schema='NhanSu')
    # ### end Alembic commands ###
