"""empty message

Revision ID: 3ce2982d9618
Revises: a8ad13b786e5
Create Date: 2020-10-08 18:34:33.011920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce2982d9618'
down_revision = 'a8ad13b786e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ViTri', 'bo_phan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ViTri', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ViTri', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ViTri', 'bo_phan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
