"""empty message

Revision ID: 45529921ba5a
Revises: 2fb37819afb5
Create Date: 2020-10-09 07:24:05.369903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45529921ba5a'
down_revision = '2fb37819afb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dm_ChucDanhCongTac',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dm_ChucDanhCongTac')
    # ### end Alembic commands ###
