"""empty message

Revision ID: 79159672bab8
Revises: c1f580d905d1
Create Date: 2020-10-08 16:45:02.467542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '79159672bab8'
down_revision = 'c1f580d905d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', mssql.BIT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
