"""empty message

Revision ID: 7946497b3a52
Revises: 2dd3eb4e7851
Create Date: 2020-10-13 10:40:21.968545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7946497b3a52'
down_revision = '2dd3eb4e7851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuiHoach',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('can_bo_id', sa.INTEGER(), nullable=True),
    sa.Column('chuc_danh_cong_tac_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['can_bo_id'], ['NhanSu.CanBo.id'], ),
    sa.ForeignKeyConstraint(['chuc_danh_cong_tac_id'], ['NhanSu.ChucDanhCongTac.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QuiHoach', schema='NhanSu')
    # ### end Alembic commands ###
