"""empty message

Revision ID: 7c1b1344cc80
Revises: 04a2aca5da47
Create Date: 2020-10-12 10:51:01.144970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1b1344cc80'
down_revision = '04a2aca5da47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=25), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['NhanSu.User.id'], name='FK__test__id__1CBC4616'),
    sa.PrimaryKeyConstraint('id', name='PK__test__3213E83F6EA014D1')
    )
    # ### end Alembic commands ###
