"""empty message

Revision ID: 842f813570b7
Revises: 1bdbb1e4095c
Create Date: 2020-10-08 16:03:01.536470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842f813570b7'
down_revision = '1bdbb1e4095c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child')
    op.drop_table('parent')
    # ### end Alembic commands ###
