"""tao csdl

Revision ID: 915fc55bc21f
Revises: 
Create Date: 2020-10-05 09:51:01.869862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915fc55bc21f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BoPhan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('ma', sa.String(length=3), nullable=True),
    sa.Column('khoi', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrangThaiUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('nam_gioi', sa.NCHAR(length=1), nullable=True),
    sa.Column('nhom_mau', sa.String(length=10), nullable=True),
    sa.Column('dantoc', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('noio', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('so_hieu', sa.String(length=6), nullable=True),
    sa.Column('ngay_vao_ca', sa.Date(), nullable=True),
    sa.Column('nganh_ngoai', sa.Boolean(), nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trang_thai_user_id', sa.SMALLINT(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['trang_thai_user_id'], ['TrangThaiUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_ten'), 'User', ['ten'], unique=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('SoDienThoai',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('so_dien_thoai', sa.NCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SoDienThoai')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_ten'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_table('TrangThaiUser')
    op.drop_table('BoPhan')
    # ### end Alembic commands ###
