"""empty message

Revision ID: 922234712369
Revises: a6388e6e0c89
Create Date: 2020-10-09 14:20:09.591674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922234712369'
down_revision = 'a6388e6e0c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BoPhan',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('ma', sa.String(length=3), nullable=True),
    sa.Column('khoi', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChucDanhCongTac',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChucDanhNghiepVu',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrangThaiUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('nam_gioi', sa.NCHAR(length=1), nullable=True),
    sa.Column('nhom_mau', sa.String(length=10), nullable=True),
    sa.Column('dan_toc', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('noi_o', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('so_hieu', sa.String(length=6), nullable=True),
    sa.Column('ngay_vao_cong_an', sa.Date(), nullable=True),
    sa.Column('nganh_ngoai', sa.Boolean(), nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trang_thai_user_id', sa.SMALLINT(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trang_thai_user_id'], ['TrangThaiUser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='nhansu'
    )
    op.create_index(op.f('ix_nhansu_User_email'), 'User', ['email'], unique=True, schema='nhansu')
    op.create_index(op.f('ix_nhansu_User_ten'), 'User', ['ten'], unique=False, schema='nhansu')
    op.create_index(op.f('ix_nhansu_User_username'), 'User', ['username'], unique=True, schema='nhansu')
    op.create_table('ChucDanhCongTacUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chuc_danh_cong_tac_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['chuc_danh_cong_tac_id'], ['ChucDanhCongTac.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nhansu.User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChucDanhNghiepVuUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chuc_danh_nghiep_vu_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['chuc_danh_nghiep_vu_id'], ['ChucDanhNghiepVu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nhansu.User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SoDienThoai',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('so_dien_thoai', sa.NCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nhansu.User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ViTri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bo_phan_id', sa.SMALLINT(), nullable=False),
    sa.Column('cong_viec', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.Column('ngay_ket_thuc', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['bo_phan_id'], ['BoPhan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nhansu.User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ViTri')
    op.drop_table('SoDienThoai')
    op.drop_table('ChucDanhNghiepVuUser')
    op.drop_table('ChucDanhCongTacUser')
    op.drop_index(op.f('ix_nhansu_User_username'), table_name='User', schema='nhansu')
    op.drop_index(op.f('ix_nhansu_User_ten'), table_name='User', schema='nhansu')
    op.drop_index(op.f('ix_nhansu_User_email'), table_name='User', schema='nhansu')
    op.drop_table('User', schema='nhansu')
    op.drop_table('TrangThaiUser')
    op.drop_table('ChucDanhNghiepVu')
    op.drop_table('ChucDanhCongTac')
    op.drop_table('BoPhan')
    # ### end Alembic commands ###
