"""empty message

Revision ID: 95805a03c78e
Revises: 7c1b1344cc80
Create Date: 2020-10-12 15:20:38.211826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95805a03c78e'
down_revision = '7c1b1344cc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('gioi_tinh', sa.NCHAR(length=1), nullable=True), schema='NhanSu')
    op.drop_column('User', 'nam_gioi', schema='NhanSu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('nam_gioi', sa.NCHAR(length=1), autoincrement=False, nullable=True), schema='NhanSu')
    op.drop_column('User', 'gioi_tinh', schema='NhanSu')
    # ### end Alembic commands ###
