"""empty message

Revision ID: 97c65307198c
Revises: 912b84d6daeb
Create Date: 2020-10-13 09:27:51.692519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c65307198c'
down_revision = '912b84d6daeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlcbTheoNam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('can_bo_id', sa.INTEGER(), nullable=True),
    sa.Column('nam', sa.SMALLINT(), nullable=True),
    sa.Column('phan_loai', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('ghi_chu', sa.NVARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['can_bo_id'], ['NhanSu.CanBo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlcbTheoNam', schema='NhanSu')
    # ### end Alembic commands ###
