"""tao bang CanBo

Revision ID: 996331167405
Revises: 
Create Date: 2020-10-04 10:26:51.432594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996331167405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('can_bo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('HoDem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('Ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_can_bo_email'), 'can_bo', ['email'], unique=True)
    op.create_index(op.f('ix_can_bo_username'), 'can_bo', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_can_bo_username'), table_name='can_bo')
    op.drop_index(op.f('ix_can_bo_email'), table_name='can_bo')
    op.drop_table('can_bo')
    # ### end Alembic commands ###
