"""empty message

Revision ID: 9caece05ccac
Revises: 35a56edf325f
Create Date: 2020-10-08 16:30:18.289481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caece05ccac'
down_revision = '35a56edf325f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('dem', sa.NVARCHAR(), nullable=True))
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_admin')
    op.drop_column('User', 'dem')
    # ### end Alembic commands ###
