"""empty message

Revision ID: a6388e6e0c89
Revises: 6f4d99a4566f
Create Date: 2020-10-09 14:17:44.630130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a6388e6e0c89'
down_revision = '6f4d99a4566f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('nam_gioi', sa.NCHAR(length=1), nullable=True),
    sa.Column('nhom_mau', sa.String(length=10), nullable=True),
    sa.Column('dan_toc', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('noi_o', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('so_hieu', sa.String(length=6), nullable=True),
    sa.Column('ngay_vao_cong_an', sa.Date(), nullable=True),
    sa.Column('nganh_ngoai', sa.Boolean(), nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trang_thai_user_id', sa.SMALLINT(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trang_thai_user_id'], ['TrangThaiUser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='nhansu'
    )
    op.create_index(op.f('ix_nhansu_User_email'), 'User', ['email'], unique=True, schema='nhansu')
    op.create_index(op.f('ix_nhansu_User_ten'), 'User', ['ten'], unique=False, schema='nhansu')
    op.create_index(op.f('ix_nhansu_User_username'), 'User', ['username'], unique=True, schema='nhansu')
    op.drop_index('ix_User_ten', table_name='User')
    op.drop_table('User')
    op.drop_constraint('FK__ChucDanhC__user___245D67DE', 'ChucDanhCongTacUser', type_='foreignkey')
    op.create_foreign_key(None, 'ChucDanhCongTacUser', 'User', ['user_id'], ['id'], referent_schema='nhansu')
    op.drop_constraint('FK__ChucDanhN__user___2A164134', 'ChucDanhNghiepVuUser', type_='foreignkey')
    op.create_foreign_key(None, 'ChucDanhNghiepVuUser', 'User', ['user_id'], ['id'], referent_schema='nhansu')
    op.drop_constraint('FK__SoDienTho__user___66603565', 'SoDienThoai', type_='foreignkey')
    op.create_foreign_key(None, 'SoDienThoai', 'User', ['user_id'], ['id'], referent_schema='nhansu')
    op.drop_constraint('FK__ViTri__user_id__6A30C649', 'ViTri', type_='foreignkey')
    op.create_foreign_key(None, 'ViTri', 'User', ['user_id'], ['id'], referent_schema='nhansu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ViTri', type_='foreignkey')
    op.create_foreign_key('FK__ViTri__user_id__6A30C649', 'ViTri', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'SoDienThoai', type_='foreignkey')
    op.create_foreign_key('FK__SoDienTho__user___66603565', 'SoDienThoai', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'ChucDanhNghiepVuUser', type_='foreignkey')
    op.create_foreign_key('FK__ChucDanhN__user___2A164134', 'ChucDanhNghiepVuUser', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'ChucDanhCongTacUser', type_='foreignkey')
    op.create_foreign_key('FK__ChucDanhC__user___245D67DE', 'ChucDanhCongTacUser', 'User', ['user_id'], ['id'])
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, mssql_identity_start=1, mssql_identity_increment=1),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ngay_sinh', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nam_gioi', sa.NCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('nhom_mau', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dan_toc', sa.NVARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('noi_o', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('so_hieu', sa.VARCHAR(length=6, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ngay_vao_cong_an', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nganh_ngoai', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trang_thai_user_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_admin', mssql.BIT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trang_thai_user_id'], ['TrangThaiUser.id'], name='FK__User__trang_thai__656C112C'),
    sa.PrimaryKeyConstraint('id', name='PK__User__3213E83F405FB3BD')
    )
    op.create_index('ix_User_ten', 'User', ['ten'], unique=False)
    op.drop_index(op.f('ix_nhansu_User_username'), table_name='User', schema='nhansu')
    op.drop_index(op.f('ix_nhansu_User_ten'), table_name='User', schema='nhansu')
    op.drop_index(op.f('ix_nhansu_User_email'), table_name='User', schema='nhansu')
    op.drop_table('User', schema='nhansu')
    # ### end Alembic commands ###
