"""empty message

Revision ID: a8ad13b786e5
Revises: 19fc8f5beffe
Create Date: 2020-10-08 18:32:07.511259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ad13b786e5'
down_revision = '19fc8f5beffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ViTri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bo_phan_id', sa.Integer(), nullable=True),
    sa.Column('cong_viec', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.Column('ngay_ket_thuc', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['bo_phan_id'], ['BoPhan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ViTri')
    # ### end Alembic commands ###
