"""empty message

Revision ID: c1f580d905d1
Revises: 66903906879a
Create Date: 2020-10-08 16:36:41.179383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f580d905d1'
down_revision = '66903906879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'User', 'TrangThaiUser', ['trang_thai_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###
