"""empty message

Revision ID: d3ff2aa3d4a6
Revises: 79159672bab8
Create Date: 2020-10-08 16:46:21.654731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ff2aa3d4a6'
down_revision = '79159672bab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###
