"""empty message

Revision ID: d86ffa0a81d1
Revises: 38a03513ac6c
Create Date: 2020-10-13 09:45:48.437257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86ffa0a81d1'
down_revision = '38a03513ac6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KiLuat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('can_bo_id', sa.INTEGER(), nullable=True),
    sa.Column('hinh_thuc', sa.NVARCHAR(), nullable=True),
    sa.Column('so_quyet_dinh', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('ngay_quyet_dinh', sa.DATE(), nullable=True),
    sa.Column('noi_dung', sa.NVARCHAR(length=250), nullable=True),
    sa.Column('ghi_chu', sa.NVARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['can_bo_id'], ['NhanSu.CanBo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('KiLuat', schema='NhanSu')
    # ### end Alembic commands ###
