"""empty message

Revision ID: e67a451a5e49
Revises: 95805a03c78e
Create Date: 2020-10-12 15:26:44.053621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67a451a5e49'
down_revision = '95805a03c78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BoPhan',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('ma', sa.VARCHAR(length=3), nullable=True),
    sa.Column('khoi', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('CapBac',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ChucDanhCongTac',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ChucDanhNghiepVu',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ChucDanhTuPhap',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('TrangThaiCongTac',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('ten', sa.NVARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ho_dem', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ten', sa.NVARCHAR(length=15), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('gioi_tinh', sa.NCHAR(length=1), nullable=True),
    sa.Column('nhom_mau', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dan_toc', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('que', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('dktt', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('noi_o', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('so_hieu', sa.VARCHAR(length=6), nullable=True),
    sa.Column('ngay_vao_cong_an', sa.Date(), nullable=True),
    sa.Column('nganh_ngoai', sa.Boolean(), nullable=True),
    sa.Column('trinh_do_chinh_tri', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_ngoai_ngu', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trinh_do_tin_hoc', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('trang_thai_cong_tac_id', sa.SMALLINT(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trang_thai_cong_tac_id'], ['NhanSu.TrangThaiCongTac.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_index(op.f('ix_NhanSu_User_email'), 'User', ['email'], unique=True, schema='NhanSu')
    op.create_index(op.f('ix_NhanSu_User_ten'), 'User', ['ten'], unique=False, schema='NhanSu')
    op.create_index(op.f('ix_NhanSu_User_username'), 'User', ['username'], unique=True, schema='NhanSu')
    op.create_table('CapBacUser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cap_bac_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['cap_bac_id'], ['NhanSu.CapBac.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ChucDanhCongTacUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chuc_danh_cong_tac_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['chuc_danh_cong_tac_id'], ['NhanSu.ChucDanhCongTac.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ChucDanhNghiepVuUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chuc_danh_nghiep_vu_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['chuc_danh_nghiep_vu_id'], ['NhanSu.ChucDanhNghiepVu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ChucDanhTuPhapUser',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chuc_danh_tu_phap_id', sa.SMALLINT(), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.Column('ngay_ket_thuc', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['chuc_danh_tu_phap_id'], ['NhanSu.ChucDanhTuPhap.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('HeSoLuongUser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('he_so', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('SoDienThoai',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('so_dien_thoai', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    op.create_table('ViTri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bo_phan_id', sa.SMALLINT(), nullable=False),
    sa.Column('cong_viec', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('ngay_bat_dau', sa.DATE(), nullable=True),
    sa.Column('ngay_ket_thuc', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['bo_phan_id'], ['NhanSu.BoPhan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['NhanSu.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='NhanSu'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ViTri', schema='NhanSu')
    op.drop_table('SoDienThoai', schema='NhanSu')
    op.drop_table('HeSoLuongUser', schema='NhanSu')
    op.drop_table('ChucDanhTuPhapUser', schema='NhanSu')
    op.drop_table('ChucDanhNghiepVuUser', schema='NhanSu')
    op.drop_table('ChucDanhCongTacUser', schema='NhanSu')
    op.drop_table('CapBacUser', schema='NhanSu')
    op.drop_index(op.f('ix_NhanSu_User_username'), table_name='User', schema='NhanSu')
    op.drop_index(op.f('ix_NhanSu_User_ten'), table_name='User', schema='NhanSu')
    op.drop_index(op.f('ix_NhanSu_User_email'), table_name='User', schema='NhanSu')
    op.drop_table('User', schema='NhanSu')
    op.drop_table('TrangThaiCongTac', schema='NhanSu')
    op.drop_table('ChucDanhTuPhap', schema='NhanSu')
    op.drop_table('ChucDanhNghiepVu', schema='NhanSu')
    op.drop_table('ChucDanhCongTac', schema='NhanSu')
    op.drop_table('CapBac', schema='NhanSu')
    op.drop_table('BoPhan', schema='NhanSu')
    # ### end Alembic commands ###
